// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wrenstone.contexts;

#nullable disable

namespace wrenstone.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20220510162900__12-28-56_10-05-2022")]
    partial class _122856_10052022
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("wrenstone.models.abstractions.Character", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("CharacterType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);

                    b.HasDiscriminator<int>("CharacterType").IsComplete(true);
                });

            modelBuilder.Entity("wrenstone.models.abstractions.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<int>("UserType").IsComplete(true);
                });

            modelBuilder.Entity("wrenstone.models.characters.DefaultCharacter", b =>
                {
                    b.HasBaseType("wrenstone.models.abstractions.Character");

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Fetched")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuildName")
                        .HasColumnType("longtext");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Race")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("wrenstone.models.users.DefaultUser", b =>
                {
                    b.HasBaseType("wrenstone.models.abstractions.User");

                    b.HasDiscriminator().HasValue(0);
                });
#pragma warning restore 612, 618
        }
    }
}
